- id: 50000000-0000-0000-0000-000000000009
  name: Cluster data destruction
  description: Simulation of the destruction of all the data of the cluster.
  tactic: impact
  technique: { attack_id: T1485, name: "Data Destruction" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0509", timeout: 30 } }