- id: 60000000-0000-0000-0000-000000000003
  name: Kubeconfig creation
  description: Creation of a kubeconfig file with Cluster Admin permission.
  tactic: persistence
  technique: { attack_id: T1098.001, name: "Account Manipulation: Additional Cloud Credentials" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0603", timeout: 900, parsers: [], cleanup: "" } }