- id: 60000000-0000-0000-0000-000000000007
  name: Secrets collection
  description: Collection of the secrets from the etcd DB.
  tactic: defense-evasion
  technique: { attack_id: T1530, name: "Data from Cloud Storage" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W607 && /opt/caldera/KC6/secrets-collection.sh", timeout: 900, parsers: [], cleanup: "" } }