- id: 60000000-0000-0000-0000-000000000008
  name: Secret Exfiltration
  description: Exfiltration of every data, secret and certificate.
  tactic: exfiltration
  technique: { attack_id: T1041, name: "Exfiltration Over C2 Channel" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W608 && /opt/caldera/KC6/exf-secrets.sh", timeout: 900, parsers: [], cleanup: "" } }