- id: 60000000-0000-0000-0000-000000000011
  name: Modify container Proxy
  description: Image modification of frontend-proxy
  tactic: privilege-escalation
  technique: { attack_id: T1543.005, name: Container Service }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0611", timeout: 900 } }