- id: 10000000-0000-0000-0000-000000000006
  name: Deploy containers using limited token
  description: Deploy container and sidecar with token.
  tactic: execution
  technique: { attack_id: T1610, name: Deploy Container }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0106", timeout: 900, parsers: [], cleanup: "" } }