- id: 40000000-0000-0000-0000-000000000002
  name: SSH Connection
  description: Shell SSH connection.
  tactic: lateral-movement
  technique: { attack_id: T1021.004, name: "Remote Services: SSH" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0402", timeout: 900, parsers: [], cleanup: "" } }