- id: 40000000-0000-0000-0000-000000000003
  name: Container analysis
  description: Container analysis of everything usefull inside.
  tactic: discovery
  technique: { attack_id: T1613, name: "Container and Resource Discovery" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W403 && ssh -p 4222 root@$(cat $DATA_PATH/KC4/attackaddr) '/usr/bin/env bash -s' < /opt/caldera/KC4/container-analysis.sh > $DATA_PATH/KC4/container-analysis.log 2>&1 && echo 'Analysis completed'", timeout: 1800, parsers: [], cleanup: "" } }