- id: 40000000-0000-0000-0000-000000000003
  name: Container analysis
  description: Container analysis of everything usefull inside.
  tactic: discovery
  technique: { attack_id: T1613, name: "Container and Resource Discovery" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0403", timeout: 1800, parsers: [], cleanup: "" } }