- id: 40000000-0000-0000-0000-000000000004
  name: Container runtime attack
  description: Exec in a container with full privileges inside the node.
  tactic: privilege-escalation
  technique: { attack_id: T1611, name: "Escape to Host" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0404", timeout: 900, parsers: [], cleanup: "" } }