- id: 40000000-0000-0000-0000-000000000007
  name: Container admin execution
  description: Using container administrator commands to obtain every information from the DBs.
  tactic: execution
  technique: { attack_id: T1609, name: "Container Administration Command" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0407", timeout: 900, parsers: [], cleanup: "" } }