- id: 40000000-0000-0000-0000-000000000008
  name: Data exfiltration
  description: Data exfiltration of the information accumulated.
  tactic: exfiltration
  technique: { attack_id: T1041, name: "Exfiltration Over C2 Channel" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "eval $KC0408", timeout: 900, parsers: [], cleanup: "" } }