- id: 30000000-0000-0000-0000-000000000005
  name: Users enumeration DB
  description: Users enumeration to the payment service for stealing precious information.
  tactic: exfiltration
  technique: { attack_id: T1020, name: "Automated Exfiltration" }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W305 && /opt/caldera/KC3/users-enum.sh", timeout: 900, parsers: [], cleanup: "" } }