- id: 20000000-0000-0000-0000-000000000001
  name: Initial Access via Wi-Fi network
  description: Simulation of the initial access in the underlay network of k8s with stolen Wi-Fi credentials.
  tactic: initial-access
  technique: { attack_id: T1669, name: Wi-Fi Networks }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W201 && echo \"[SIM] initial access with stolen Wi-Fi credentials\"", timeout: 30 } }