- id: 20000000-0000-0000-0000-000000000004
  name: Password enumeration
  description: Password enumeration of registry server.
  tactic: credential-access
  technique: { attack_id: T1110.001, name: Password Guessing }
  repeatable: false
  singleton: true
  platforms:
    linux: { sh: { command: "sleep $W204 && /opt/caldera/KC2/pass-enum.sh", timeout: 1200, parsers: [], cleanup: "" } }